// Recipe migration (doc 11, debt opened by R4). A recipe that GROWS a section
// used to strand every document generated before it: `init` never overwrites an
// existing file and `sync` only regenerates regions that already exist, so the
// only way to get the new section was to delete the file and re-init - which is
// lossless exactly until someone has written prose into a slot or below the
// human-notes marker, and then it destroys their work.
//
// This pass inserts the missing SECTIONS in place. Its whole discipline is
// negative: it never rewrites an existing region (that is drift's job and
// sync's), never reorders, never touches a byte outside the range it inserts,
// and never writes into a document keeldocs did not generate. A section is
// identified by the marker ids inside it, not by its heading text, so renaming
// a heading by hand does not resurrect a duplicate.
//
// Anchoring is SEMANTIC, not positional: a proposal records the marker id it
// must follow, resolved against the document as it stands at apply time. That
// survives earlier insertions in the same run, and it lets a run of new
// sections chain onto each other in recipe order.

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parseDoc } from "./anchors.js";
import { renderAll } from "./render.js";

const HUMAN_MARKER = "<!-- Human notes below this line are never touched by keeldocs. -->";
const isHeading = (line) => /^## /.test(line);

// Ordered `## ` sections of a generated doc, keyed by the marker ids they
// carry. Everything at or after the human-notes marker is outside the recipe's
// territory and is never a section: the whole point of that line is that the
// tool stops there.
export function sectionsOf(text, docPath) {
  const lines = text.split("\n");
  const { anchors, regions } = parseDoc(text, docPath);
  const marks = [...anchors, ...regions]
    .map((m) => ({ line: m.line, id: m.id })).sort((a, b) => a.line - b.line);
  const humanIdx = lines.findIndex((l) => l.trim() === HUMAN_MARKER);
  const limit = humanIdx === -1 ? lines.length : humanIdx;
  const heads = [];
  for (let i = 0; i < limit; i++) if (isHeading(lines[i])) heads.push(i);
  const sections = heads.map((start, k) => {
    const end = k + 1 < heads.length ? heads[k + 1] : limit; // exclusive
    const ids = marks.filter((m) => m.line - 1 >= start && m.line - 1 < end).map((m) => m.id);
    return { heading: lines[start].replace(/^##\s*/, ""), start, end, ids, key: ids[0] ?? null };
  });
  return { lines, limit, sections, allIds: new Set(marks.map((m) => m.id)) };
}

// Insert `body` (an array of lines, heading first) relative to an anchor that
// is resolved in the CURRENT text. Throws rather than guessing - a document we
// cannot locate a position in is one we must not write to.
export function applyInsertion(text, docPath, { anchor, anchorId, body }) {
  const doc = sectionsOf(text, docPath);
  let at;
  if (anchor === "end") {
    at = doc.limit;
  } else {
    const target = doc.sections.find((s) => s.ids.includes(anchorId));
    if (!target) {
      throw new Error(`anchor section for \`${anchorId}\` is not in ${docPath} yet - apply that section first`);
    }
    at = anchor === "after" ? target.end : target.start;
  }
  const lines = [...doc.lines];
  lines.splice(at, 0, ...body);
  return lines.join("\n");
}

// Plan the whole upgrade. Returns proposals in RECIPE ORDER per document -
// applying them in that order is what lets a run of consecutive new sections
// anchor onto each other.
export function planUpgrade({ root, factsById, journal, sink }) {
  const rendered = renderAll(factsById, sink);
  const proposals = [], missingDocs = [], skipped = [];

  for (const r of rendered) {
    const abs = join(root, r.path);
    if (!existsSync(abs)) { missingDocs.push(r.path); continue; }
    const diskText = readFileSync(abs, "utf8");
    const fresh = sectionsOf(r.content, r.path);
    const disk = sectionsOf(diskText, r.path);

    // Ownership proof: the recipe's own root anchor must already be in the
    // file. A same-named document somebody else wrote is not ours to edit.
    const rootId = parseDoc(r.content, r.path).anchors[0]?.id;
    if (!rootId || !disk.allIds.has(rootId)) {
      if (fresh.sections.some((s) => s.key && !disk.allIds.has(s.key))) {
        skipped.push({ doc: r.path, id: rootId ?? "?", reason: "not generated by keeldocs (root anchor absent)" });
      }
      continue;
    }

    // A section is missing when NONE of its marker ids are in the document.
    // Testing every id, not just the heading, is what makes this idempotent
    // and safe against a hand-renamed heading.
    const planned = new Set();
    for (let i = 0; i < fresh.sections.length; i++) {
      const s = fresh.sections[i];
      if (!s.key || s.ids.some((id) => disk.allIds.has(id))) continue;
      if (journal?.rejection?.has(s.key)) {
        skipped.push({ doc: r.path, id: s.key, reason: "rejected earlier - a recorded decision is not re-proposed" });
        continue;
      }
      if (journal?.snooze?.has(s.key)) {
        skipped.push({ doc: r.path, id: s.key, reason: "snoozed" });
        continue;
      }
      // Anchor to the nearest neighbour that either already exists or is
      // itself being inserted ahead of this one, preferring the predecessor so
      // the document ends up in recipe order.
      let anchor = "end", anchorId = null;
      for (let j = i - 1; j >= 0; j--) {
        const k = fresh.sections[j].key;
        if (k && (disk.allIds.has(k) || planned.has(k))) { anchor = "after"; anchorId = k; break; }
      }
      if (anchorId === null) {
        for (let j = i + 1; j < fresh.sections.length; j++) {
          const k = fresh.sections[j].key;
          if (k && disk.allIds.has(k)) { anchor = "before"; anchorId = k; break; }
        }
      }
      planned.add(s.key);
      proposals.push({
        kind: "insert-section", id: s.key, doc: r.path, line: 1,
        heading: s.heading, anchor, anchorId,
        body: fresh.lines.slice(s.start, s.end),
        evidence: `this document predates the \`## ${s.heading}\` section of recipe ${rootId}; ` +
          (anchor === "end"
            ? "appending it above the human-notes line"
            : `inserting it ${anchor} \`${anchorId}\``) +
          " - no existing byte changes",
      });
    }
  }
  return { proposals, missingDocs, skipped };
}
